deployment:
  tasks:
    - source /home/geohzdwu/virtualenv/api.geohabita.com/app/3.10/bin/activate && pip install -r requirements.txt
    - source /home/geohzdwu/virtualenv/api.geohabita.com/app/3.10/bin/activate && python manage.py migrate --noinput
    - source /home/geohzdwu/virtualenv/api.geohabita.com/app/3.10/bin/activate && python manage.py collectstatic --noinput
    - touch tmp/restart.txt
