# Generated by Django 5.2.4 on 2025-07-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('idimagenes', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'imagenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inmobilaria',
            fields=[
                ('idinmobilaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreinmobiliaria', models.CharField(blank=True, db_column='nombreInmobiliaria', max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True)),
                ('pagina', models.CharField(blank=True, max_length=200, null=True)),
                ('latitud', models.CharField(blank=True, max_length=25, null=True)),
                ('longitud', models.CharField(blank=True, max_length=25, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=450, null=True)),
            ],
            options={
                'db_table': 'inmobilaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('idpuntos', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.CharField(blank=True, max_length=25, null=True)),
                ('longitud', models.CharField(blank=True, max_length=25, null=True)),
                ('lado_metros', models.FloatField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'puntos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInmobiliaria',
            fields=[
                ('idtipoinmobiliaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_inmobiliaria',
                'managed': False,
            },
        ),
    ]
