# Generated by Django 5.2.4 on 2025-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('idlote', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('latitud', models.CharField(blank=True, max_length=45, null=True)),
                ('longitud', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'lote',
                'managed': False,
            },
        ),
    ]
