# Generated by Django 5.2.7 on 2026-05-22 03:24

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_create_espacios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickProyectos',
            fields=[
                ('idclickProyectos', models.AutoField(db_column='idclickProyectos', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('click', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'clickproyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClicksContactos',
            fields=[
                ('idclicksContactos', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('click', models.PositiveIntegerField(default=1)),
                ('redSocial', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'clickscontactos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotspot360',
            fields=[
                ('id_hotspot', models.AutoField(primary_key=True, serialize=False)),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('texto_ayuda', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'hotspots_360',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IconoProyecto',
            fields=[
                ('idiconoproyecto', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.CharField(blank=True, max_length=50, null=True)),
                ('longitud', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'iconoproyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagen360',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, db_column='url', max_length=500, null=True, upload_to=api.models.upload_imagen360_casas)),
                ('yaw', models.FloatField(help_text='Posición horizontal')),
                ('pitch', models.FloatField(help_text='Posición vertical')),
                ('overlays_2d', models.TextField(blank=True, db_column='overlays_2d', null=True)),
                ('texto_ayuda', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'imagenes_360',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('idimagenes', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=api.models.upload_lote_image)),
            ],
            options={
                'db_table': 'imagenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenesProyecto',
            fields=[
                ('idimagenesp', models.AutoField(primary_key=True, serialize=False)),
                ('imagenproyecto', models.ImageField(blank=True, null=True, upload_to=api.models.upload_proyecto_image)),
            ],
            options={
                'db_table': 'imagenesproyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inmobiliaria',
            fields=[
                ('idinmobiliaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreinmobiliaria', models.CharField(blank=True, db_column='nombreInmobiliaria', max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('pagina', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=450)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inmobiliaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('idlote', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=2000, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('latitud', models.CharField(blank=True, max_length=45, null=True)),
                ('longitud', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('vendido', models.IntegerField(blank=True, null=True)),
                ('area_total_m2', models.CharField(blank=True, max_length=60, null=True)),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('banos', models.IntegerField(blank=True, null=True)),
                ('cuartos', models.IntegerField(blank=True, null=True)),
                ('titulo_propiedad', models.IntegerField(blank=True, null=True)),
                ('cochera', models.IntegerField(blank=True, null=True)),
                ('cocina', models.IntegerField(blank=True, null=True)),
                ('sala', models.IntegerField(blank=True, null=True)),
                ('patio', models.IntegerField(blank=True, null=True)),
                ('jardin', models.IntegerField(blank=True, null=True)),
                ('terraza', models.IntegerField(blank=True, null=True)),
                ('azotea', models.IntegerField(blank=True, null=True)),
                ('ancho', models.FloatField(blank=True, null=True)),
                ('largo', models.FloatField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=80, null=True)),
                ('bandera', models.CharField(blank=True, max_length=500, null=True)),
                ('moneda', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'lote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('idpuntos', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.CharField(blank=True, max_length=25, null=True)),
                ('longitud', models.CharField(blank=True, max_length=25, null=True)),
                ('lado_metros', models.FloatField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'puntos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntosProyecto',
            fields=[
                ('idpunto', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'puntosproyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInmobiliaria',
            fields=[
                ('idtipoinmobiliaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_inmobiliaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iconos',
            fields=[
                ('idiconos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='iconos/')),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'iconos',
                'managed': True,
            },
        ),
    ]
