# Generated by Codex on 2026-05-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_clickproyectos_clickscontactos_hotspot360_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoExtraccionCache",
            fields=[
                ("idplanoextraccioncache", models.AutoField(primary_key=True, serialize=False)),
                ("request_signature", models.CharField(max_length=64, unique=True)),
                ("extraction_version", models.CharField(default="v2_labels", max_length=32)),
                ("status", models.CharField(default="completed", max_length=20)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idproyecto",
                    models.ForeignKey(
                        db_column="idproyecto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planos_extraccion_cache",
                        to="api.proyecto",
                    ),
                ),
            ],
            options={
                "db_table": "plano_extraccion_cache",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="planoextraccioncache",
            index=models.Index(fields=["idproyecto", "updated_at"], name="plano_extr_idproye_81f9ee_idx"),
        ),
        migrations.AddIndex(
            model_name="planoextraccioncache",
            index=models.Index(fields=["request_signature"], name="plano_extr_reques_09ebf3_idx"),
        ),
        migrations.AddIndex(
            model_name="planoextraccioncache",
            index=models.Index(fields=["status"], name="plano_extr_status_e25538_idx"),
        ),
    ]
