# Generated by Django 5.2.7 on 2026-05-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_planoextraccioncache'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('idblockedip', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=80, unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('risk_score', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blocked_ip',
                'managed': True,
                'indexes': [models.Index(fields=['ip_address', 'is_active'], name='blocked_ip_ip_addr_8e7375_idx'), models.Index(fields=['expires_at', 'is_active'], name='blocked_ip_expires_c9b706_idx'), models.Index(fields=['risk_score'], name='blocked_ip_risk_sc_819463_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('idsecurityevent', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(db_index=True, max_length=80)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('risk_score', models.IntegerField(default=0)),
                ('action', models.CharField(default='score', max_length=40)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'security_event',
                'managed': True,
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='security_ev_ip_addr_78dcc2_idx'), models.Index(fields=['event_type', 'created_at'], name='security_ev_event_t_f2ceb3_idx'), models.Index(fields=['action', 'created_at'], name='security_ev_action_6f1bdd_idx')],
            },
        ),
    ]
