name: Deploy Django to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/geohzdwu/api.geohabita.com/app

            git pull origin main

            source /home/geohzdwu/virtualenv/api.geohabita.com/app/3.10/bin/activate
            pip install -r requirements.txt

            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            touch tmp/restart.txt
